"""add age to users

Revision ID: 037e9a8134ee
Revises: 2bd992bc775f
Create Date: 2026-06-25 23:15:50.427559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037e9a8134ee'
down_revision: Union[str, Sequence[str], None] = '2bd992bc775f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'age')
    # ### end Alembic commands ###
